services:
  postgres:
    image: postgres:16-alpine
    container_name: lemon-postgres
    environment:
      POSTGRES_USER: lemon_user
      POSTGRES_PASSWORD: lemon_password
      POSTGRES_DB: lemon_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db-init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: