export const CLIENTE_ID_CONFLICT = 'CLIENTE_ID_CONFLICT'

export const CLIENTE_NUMERO_DOCUMENTO_CONFLICT = 'CLIENTE_NUMERO_DOCUMENTO_CONFLICT'

export const CLIENTE_NUMERO_TELEFONO_CONFLICT = 'CLIENTE_NUMERO_TELEFONO_CONFLICT'

export const CLIENTE_CORREO_ELECTRONICO_CONFLICT = 'CLIENTE_CORREO_ELECTRONICO_CONFLICT'